EMAIL_DEFAULT = 'm89067536142@yandex.ru'
PASSWORD_DEFAULT = '123456'
NAME_DEFAULT = 'Mf'
RESPONSE_CODE_200 = 200
PART_OF_TEXT_CREATE_AND_CHANGING_USER_200 = '{"success":true,"user":{"email":'
PART_OF_TEXT_CREATE_USER_SIGN_IN_200 = '{"success":true,"accessToken":"Bearer'
PART_OF_TEXT_CREATE_USER_ORDER_200 = '{"success":true,"name":'
PART_OF_TEXT_CREATE_USER_GET_LIST_ORDER_200 = '{"success":true,"orders":'
RESPONSE_CODE_400 = 400
TEXT_USER_CREATE_ORDER_NO_INGREDIENTS_400 = '{"success":false,"message":"Ingredient ids must be provided"}'
RESPONSE_CODE_401 = 401
TEXT_NO_AUTORIZATION_401 = '{"success":false,"message":"You should be authorised"}'
TEXT_NO_AUTORIZATION_WITH_INCORRECT_LOGIN_PASSWORD_401 = '{"success":false,"message":"email or password are incorrect"}'
RESPONSE_CODE_403 = 403
TEXT_CREATE_CREATED_USER_403 = '{"success":false,"message":"User already exists"}'
TEXT_CHANGING_USER_WITH_CREATED_EMAIL_403 = '{"success":false,"message":"User with such email already exists"}'
TEXT_CREATE_USER_WITHOUT_REQUIRED_FIELD_403 = '{"success":false,"message":"Email, password and name are required fields"}'
RESPONSE_CODE_500 = 500
PART_OF_TEXT_500 = 'Internal Server Error'
